server:
  port: 9797
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: sudo
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql : true
      hibernate.ddl-auto: create-drop